# variables:
#   MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

cache:
  paths:
    - .m2/repository
    - target

stages:
  - build
  - dockerize
  # - test
  # -package
  # -deploy

build_job:
  stage: build
  tags:
    - maven

  script:
    - echo "starting build"
    - "mvn compile"

dockerize_job:
  stage: dockerize
  tags:
    - docker
  
  script:
    - echo "start building container..."
    - "docker info"
    # - "docker build -t rikdegoede/pokemonCardMarkt ."
    # - "docker push rikdegoede/pokemonCardMarkt"

# test_job:
#   stage: test
#   tags:
#     - maven

#   script:
#     - echo "started testing"
#     - "mvn test"

# package_job:
#   stage: package
#   tags:
#     - docker

  # script:
  #   - echo "packaging stage started"
  #   - "mvn package"

