image: maven:3.3.9-jdk-8


cache:
  paths:
    - .m2/repository

stages:
  -build
  -test
  -package
  -deploy

build_job:
  stage: build
  tags:
    - docker

  script:
    - echo "starting build"
    - "mvn compile"

test_job:
  stage: test
  tags:
    - docker

  script:
    - echo "started testing"
    - "mvn test"

package_job:
  stage: package
  tags:
    - docker

  script:
    - echo "packaging stage started"
    - "mvn package"

deploy_job:
  stage: deploy

  tags:
    - docker

  script:
    - echo "started deploying"