image: maven:latest 

cache:
  paths:
    - .m2/repository
    - target

stages:
  - build
  - test
  - dockerize

build_job:
  stage: build
  tags:
    - maven

  script:
    - echo "starting build"
    # - "mvn compile"

test_job:
  stage: test
  tags:
    - maven
  
  script:
    - echo "start testing"
    - "mvn test"

dockerize_job:
  image: docker:latest
  stage: dockerize
  tags:
    - docker
  
  services:
    - docker:dind
  
  before_script:
     - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" 
  
  # should be cmd, not script
  script:
    - echo "start building container..."
    # - "docker info"
    - "docker build -t rikdegoede/pokemon-card-market-backend ."
    # - "docker login $DOCKER_USERNAME"  #$DOCKER_PASSWORD
    - "docker push rikdegoede/pokemon-card-market-backend"
